name: Continuous Integration

on:
  pull_request:
    branches:
      ["master"]
  push:
    branches:
      ["master"]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.1.0
      - name: run install and test
        run: |
          npm install
          npm run test


